### PR TITLE
Feature/integration tests

### PR DESCRIPTION
**Pull request by diogopcx**

### CODE REVIEW

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by cxflowtestuser** [comment]
Logo<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 8 vulnerabilities<br />High&nbsp;**0 High**<br />Medium&nbsp;**0 Medium**<br />Low&nbsp;**8 Low**<br />Info&nbsp;**0 Info**<br />
### Violation Summary
#### No policy violation found
***
Logo
**Checkmarx SCA - Scan Summary & Details**
### Cx-SCA Summary
**Total Packages Identified**: **0**
**Scan Risk Score**: **0.00**

High&nbsp;**0** **High** **severity vulnerabilities**
Medium&nbsp;**0** **Medium** **severity vulnerabilities**
Low&nbsp;**0** **Low** **severity vulnerabilities**
[View more details on Checkmarx UI](https://eu.sca.checkmarx.net/#/projects/ca5365a8-3abb-442d-a5b2-35ecb5c6d743/reports/2c1ddbdd-c240-4225-a925-ddfdd6e210c1)
### Cx-SCA vulnerability result overview
#### No package violation found

**Review by tsunez — APPROVED** [review]
Definitely very large PR but it looks like what we discussed.  I think it all makes sense, the only area I wonder about is the removal of the health check and log support. I know the health check support was working and the API is supposed to be returned.

**Comment by pedrompflopes** [comment]
> Definitely very large PR but it looks like what we discussed. I think it all makes sense, the only area I wonder about is the removal of the health check and log support. I know the health check support was working and the API is supposed to be returned.

We spoke with James, since it is always returning an error in one service and we don't use it, we will remove it and maybe put it back in the future.

**Pull request merged**
